AS=a86
GAME_SRCS=game.8
BANKED_SRCS=banked.8

all: game banked

game: $(GAME_SRCS)
    $(AS) $(GAME_SRCS)

banked: $(BANKED_SRCS)
    $(AS) $(BANKED_SRCS)

clean:
    del *.obj
    del *.com
    del *.exe
    del *.lst
    del *.sym
    del *.xrf
    del *.err
    del *.bak
    del *.old
    del *.und
